{
 "title": "Backstage OpenTelemetry by Namespace (Prometheus Operator)",
 "description": "This is a showcase of the various metrics provided by Backstage along with auto instrumented metrics to help setup observability for your Backstage instance!",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data  source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(catalog_entities_count{job=\"backstage\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server request availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(sum(count_over_time((http_server_duration_count{namespace=\"$namespace\",service=\"backstage\",http_status_code=~\"(5..|429)\"})[5m:])) OR on() vector(0))\r\n/\r\n(sum(count_over_time((http_server_duration_count{namespace=\"$namespace\",service=\"backstage\"})[5m:])))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Client Requests Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(sum(count_over_time((http_client_duration_count{namespace=\"$namespace\",service=\"backstage\",http_status_code=~\"(5..|4..)\"})[5m:])) OR on() vector(0))\r\n/\r\n(sum(count_over_time((http_client_duration_count{namespace=\"$namespace\",service=\"backstage\"})[5m:])))",
     "legendFormat": "errors"
    }
   ]
  },
  { "title": "Catalog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Catalog Entities Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(catalog_entities_count{namespace=\"$namespace\"}) by(kind)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Catalog Processing Queue Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(rate(catalog_processing_queue_delay_sum{namespace=\"$namespace\"}[1m]) / rate(catalog_processing_queue_delay_count{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Catalog Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "max(rate(catalog_processing_duration_sum{namespace=\"$namespace\"}[1m]) / rate(catalog_processing_duration_count{namespace=\"$namespace\"}[1m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Catalog Processed Entities Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(irate(catalog_processed_entities_count_total{namespace=\"$namespace\"}[5m])) by(result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Catalog Stitching Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "max(catalog_stitching_queue_length{namespace=\"$namespace\"}) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Catalog Entities Stitched Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "targets": [
    {
     "expr": "sum(irate(catalog_stitched_entities_count_total{namespace=\"$namespace\"}[5m])) by(namespace, result)",
     "legendFormat": "{{namespace}}: {{result}}"
    }
   ]
  },
  {
   "title": "Catalog Stitching Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "targets": [
    {
     "expr": "max(rate(catalog_stitching_duration_sum{namespace=\"$namespace\"}[1m]) / rate(catalog_stitching_duration_count{namespace=\"$namespace\"}[1m])) by (namespace, result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Backend Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Backend Tasks Time Since Scheduler Task Start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "time() - (max(backend_tasks_task_runs_started{namespace=\"$namespace\"}) by (pod, taskId))",
     "legendFormat": "{{pod}}: {{taskId}}"
    }
   ]
  },
  {
   "title": "Backend Tasks Runs Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "max(backend_tasks_task_runs_started{namespace=\"$namespace\"}) by(taskId)",
     "legendFormat": "{{taskId}}"
    }
   ]
  },
  {
   "title": "Backend Tasks Runs Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "max(backend_tasks_task_runs_completed{namespace=\"$namespace\"}) by(taskId)",
     "legendFormat": "{{taskId}}"
    }
   ]
  },
  { "title": "Scaffolder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Scaffolder Step Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "max(scaffolder_step_count_total{namespace=\"$namespace\"}) by (template, step)",
     "legendFormat": "{{namespace}}/{{template}} - {{step}}"
    }
   ]
  },
  {
   "title": "Scaffolder Task Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "max(scaffolder_task_count_total{namespace=\"$namespace\"}) by (template)",
     "legendFormat": "{{template}}"
    }
   ]
  }
 ]
}