apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: alithya-oss/backstage-demo
    # backstage.io/techdocs-ref: dir:.
    prometheus.io/alert:
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
