services:
  # postgres:
  #   env_file: ./.env
  #   build:
  #     context: containers/pgvector
  #   image: oci.local/postgresql/pgvector:dev
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-backstage}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-backstage_user}
  #     POSTGRES_POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD:-postgres_admin}
  #     POSTGRES_REPLICATION_PASSWORD: ${POSTGRES_REPLICATION_PASSWORD:-postgre_replication}
  #     POSTGRES_DB: ${POSTGRES_DB:-postgres}
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - backstage-postgres:/var/lib/postgresql/data

  # cache:
  #   env_file: ./.env
  #   image: docker.io/bitnami/valkey:latest
  #   environment:
  #     VALKEY_PASSWORD: ${REDIS_PASSWORD:-backstkage_valkey}
  #   ports:
  #     - '${REDIS_PORT:-6379}:6379'
  #   volumes:
  #     - backstage-redis:/data

  # jaeger:
  #   image: quay.io/jaegertracing/all-in-one:latest
  #   restart: always
  #   environment:
  #     LOG_LEVEL: debug
  #     COLLECTOR_OTLP_ENABLED: 'true'
  #   ports:
  #     - '${JARGER_WEBUI_PORT:-16686}:16686'
  #     - '${OTLP_EXPORTER_PORT:-4317}:4317'
  #     - '${OTLP_EXPORTER_GRPC_PORT:-4318}:4318'

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "Complexpass#123"
    ports:
      - "35080:5080"
    volumes:
      - backstage-openobserve:/data

  prometheus:
    image: docker.io/prom/prometheus:latest
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${PROMETHEUS_PORT:-9090}:9090'
    volumes:
      - ./examples/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./examples/prometheus/backstage-rules.yml:/etc/prometheus/backstage-rules.yml
    depends_on:
      - openobserve

  promlens:
    image: docker.io/prom/promlens:latest
    ports:
      - '${PROMLENS_PORT:-8080}:8080'
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 43000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/backstage.json
    volumes:
      - ./examples/grafana/dashboards:/etc/grafana/provisioning/dashboards/
      - ./examples/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      - prometheus

volumes:
  # backstage-postgres:
  #   driver: local
  # backstage-redis:
  #   driver: local
  backstage-prometheus:
    driver: local
  backstage-openobserve:
    driver: local