---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage
subjects:
  - namespace: backstage
    kind: ServiceAccount
    name: backstage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:aggregate-to-view
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: backstage
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: backstage-env
#   namespace: backstage
# type: Opaque
# data:
#   GITHUB_TOKEN: __BASE64_CHANGE_ME__