---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: developer-portal
spec:
  owner: group:default/devex
  domain: developer-experience
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: Backstage
  name: backstage
  description: An example of a Backstage application backend.
  # Example for optional annotations
  annotations:
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/component=backstage'
    github.com/project-slug: alithya-oss/backstage-demo
    # backstage.io/techdocs-ref: dir:.
    prometheus.io/alert: BackstageHighErrorRate
    prometheus.io/rule: slo:sli_error:ratio_rate5m{sloth_service="default-backstage"}
    
    argocd/app-name: backstage
spec:
  system: developer-portal
  type: service
  owner: group:default/devex
  lifecycle: experimental
  providesApis:
    - internal_backstage_openapi_doc
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: Backstage SPA
  name: backstage-app
  description: An example of a Backstage application frontend.
  # Example for optional annotations
  annotations:
    github.com/project-slug: alithya-oss/backstage-demo
    # backstage.io/techdocs-ref: dir:.
    argocd/app-name: backstage
spec:
  system: developer-portal
  type: website
  owner: group:default/devex
  lifecycle: experimental